### ISSUE TITLE
Create a list and store it in a text file

### ISSUE THREAD

**Issue by clarkngo** [maryoohhh/homeproj1#2]
Use `list` data structure in Python and store it in a `.txt` file.

Create a python file named `macaroon_ingredients.py`. 👩‍🍳

Give me a list of ingredients needed to bake macarons.

keywords to search in google:
- `list` in python
- enhanced for loop in python `for ... in`

Example:
```
ingredients = ['item1', 'item2', 'item3']
file = open('macaron_ingredients', 'w')
for item in ingredients:
  file.write(item + '\n')
f.close()
```
Note: change the items in the `list` with real ingredients please. Yum! 😋

To run your code, in your terminal:
```
python macaron_ingredients.py
```
Note: if `python` keyword did not work, try `python3`

To view this in your terminal:
```
cat macaron_ingredients.txt
```

When you are done, please paste a screenshot in the comment below of your output with `cat macaron_ingredients.txt`.

**Comment by maryoohhh** [comment]
![Screen Shot 2020-03-31 at 4 49 19 PM](https://user-images.githubusercontent.com/26679219/78085383-ab41c600-736f-11ea-9b75-653b5120da30.png)
